trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroup: 'schoolargroup'
  acrName: 'schoolaracr'
  imageName: 'schoolar-api'
  imageTag: 'v1'

stages:
- stage: BuildAndTest
  displayName: 'Build and Run Tests'
  jobs:
  - job: BuildAndTest
    displayName: 'Build and Test'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        goals: 'clean package' # Isso irá construir e testar o projeto
      displayName: 'Maven build and test with JDK 17'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/target' # Publica os artefatos da pasta target
        artifact: 'spring-boot-artifact'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: 'Deploy Container'
  condition: succeeded('BuildAndTest')
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'spring-boot-artifact'
        targetPath: '$(System.DefaultWorkingDirectory)/target' # Baixa os artefatos para a pasta target
    - task: AzureContainerApps@1
      inputs:
        appSourcePath: '.'
        azureSubscription: 'Azure for Students(2)(5346ca21-c31a-4db1-86f5-012204b8c727)'
        acrName: 'schoolaracr'
        acrUsername: 'schoolaracr'
        acrPassword: 'emprE4Z3i1gvMrfN7SVrjIPx2ypB7FWgNl8/WUNw1H+ACRCcnh3o'
        dockerfilePath: 'Dockerfile'
        imageToBuild: 'schoolaracr.azurecr.io/schoolar-api:v1'
        imageToDeploy: 'schoolaracr.azurecr.io/schoolar-api:v1'
        containerAppName: 'schoolar-api'
        resourceGroup: 'schoolargroup'
        containerAppEnvironment: 'schoolar-api'
        runtimeStack: ''
        targetPort: '8080'
        location: 'eastus'
        ingress: 'external'
