trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Definindo as variáveis necessárias
  resourceGroup: 'schoolargroup'
  acrName: 'schoolaracr'
  imageName: 'schoolar-api'
  imageTag: 'v1'

stages:
- stage: PreBuild
  displayName: 'Pre-Build Validation'
  jobs:
  - job: Validate
    displayName: 'Validate Access'
    steps:
    - bash: az --version
      displayName: 'Show Azure CLI version'
    - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
      displayName: 'Set default Azure DevOps organization and project'
    - bash: |
        az pipelines build list
        git pr list
      displayName: 'Show build list and PRs'
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'
      displayName: 'Maven build with JDK 17'
    - script: |
        echo $(azureDevOpsPAT) | az devops login
        az acr login --name $(acrName)
        docker build -t $(imageName) .
        docker tag $(imageName) $(acrName).azurecr.io/$(imageName):$(imageTag)
        docker push $(acrName).azurecr.io/$(imageName):$(imageTag)
      displayName: 'Authenticate and push image to ACR'
      env:
        AZURE_DEVOPS_EXT_PAT: $(azureDevOpsPAT)

- stage: Deploy
  displayName: 'Deploy Container'
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    steps:
    - script: |
        az container create --resource-group $(resourceGroup) --name $(imageName) --image $(acrName).azurecr.io/$(imageName):$(imageTag) --cpu 1 --memory 1 --ports 8080 --ip-address public
      displayName: 'Create Azure Container Instance'
