trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Definindo as variáveis necessárias
  resourceGroup: 'schoolargroup'
  acrName: 'schoolaracr'
  imageName: 'schoolar-api'
  imageTag: 'v1'

stages:
- stage: PreBuild
  displayName: 'Pre-Build Validation'
  jobs:
  - job: Validate
    displayName: 'Validate Access'
    steps:
    - pwsh: |
        az pipelines build list
      displayName: 'Show build list'
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - script: |
        mvn clean install
        docker build -t $(imageName) .
        az acr login --name $(acrName)
        docker tag $(imageName) $(acrName).azurecr.io/$(imageName):$(imageTag)
        docker push $(acrName).azurecr.io/$(imageName):$(imageTag)
      displayName: 'Build and push image to ACR'

- stage: Deploy
  displayName: 'Deploy Container'
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    steps:
    - script: |
        az container create --resource-group $(resourceGroup) --name $(imageName) --image $(acrName).azurecr.io/$(imageName):$(imageTag) --cpu 1 --memory 1 --ports 8080 --ip-address public
      displayName: 'Create Azure Container Instance'
